# try
# except
# else
# finally

print("Exceções no python!")
print("bloco try", "- except", "- else", "- finally")
